### ISSUE TITLE
Rename All name Properties to node_name or name on schema_config.yaml and also on the data

### ISSUE THREAD

**Issue by eyasubirhanu** [rejuve-bio/biocypher-metta#1]
#### Description
There is inconsistency in the schema file and the data. For example, in the data, the name property is referred to as `gene_name`, but in the schema file, it is just `name`. To address these inconsistencies, we need to rename all instances of the `name` property to `node_name` as appropriate.

#### Proposed Changes

- For the entities, rename the name property in the `schema_config.yaml` file to node_name.
- Update the actual data to match these new property names.

##### Gene
```yaml
gene:
  represented_as: node
  preferred_id: ensemble
  input_label: gene
  is_a: coding element
  inherit_properties: true
  properties:
    gene_name: str
    gene_type: str
```

##### Protein
```yaml
protein:
  represented_as: node
  preferred_id: uniprot
  input_label: protein
  is_a: coding element
  properties:
    accessions: int
    organism_id: int
    protein_name: str
    source: str
    source_url: str
```
